create table tb_worker (id int8 generated by default as identity, daily_income numeric(19, 2), name varchar(255), primary key (id));
create table tb_worker (id int8 generated by default as identity, daily_income numeric(19, 2), name varchar(255), primary key (id));
create table tb_worker (id int8 generated by default as identity, daily_income numeric(19, 2), name varchar(255), primary key (id));
